[target.wasm32-unknown-emscripten]
rustflags = [
    "-Clink-args=-sMAIN_MODULE=2 --pre-js pre.js -sALLOW_MEMORY_GROWTH=1 -sEXPORTED_FUNCTIONS=['_main'] -sASSERTIONS=1 -sABORTING_MALLOC=0 -sDISABLE_EXCEPTION_CATCHING=0 -sERROR_ON_UNDEFINED_SYMBOLS=0 -o hello_world.html",
]
