[target.wasm32-unknown-emscripten]
rustflags = [
    "-Csymbol-mangling-version=v0",
    "-Clink-args=-sMAIN_MODULE=1 --pre-js pre.js -sALLOW_MEMORY_GROWTH=1 -sEXPORTED_FUNCTIONS=['_main'] -sASSERTIONS=1 -sABORTING_MALLOC=0 -sDISABLE_EXCEPTION_CATCHING=0 -sERROR_ON_UNDEFINED_SYMBOLS=0 -o hello_world.html",
]

[unstable]
build-std = ["std", "panic_abort"]
